sonar.organization=cristianat98
sonar.projectKey=cristianat98_ZTE-Exporter

sonar.sources=.
sonar.exclusions=**/*_test.go,docs/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
